replicaCount: 1

backend:
  image: dimeblyat/backend
  tag: 96fd2c39b3a7d67f19971b7e3af27885cf4b2f75
  servicePort: 5000

ingress:
  host: myapp.local

postgresql:
  enabled: false
  image:
    registry: docker.io
    repository: postgres
    tag: 96fd2c39b3a7d67f19971b7e3af27885cf4b2f75
  global:
    security:
      allowInsecureImages: true
  primary:
    persistence:
      enabled: false
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
