replicaCount: 1

backend:
  image: dimeblyat/backend
  tag: 58ba39d77049656bd64c458467e639d64772a868
  servicePort: 5000

ingress:
  host: myapp.local

postgresql:
  enabled: false
  image:
    registry: docker.io
    repository: postgres
    tag: 58ba39d77049656bd64c458467e639d64772a868
  global:
    security:
      allowInsecureImages: true
  primary:
    persistence:
      enabled: false
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
