replicaCount: 1

frontend:
  image: frontend-image
  tag: latest
  servicePort: 80

backend:
  image: backend-image
  tag: latest
  servicePort: 5000

ingress:
  host: myapp.local

postgresql:
  image:
    registry: docker.io
    repository: postgres
    tag: "16"
  global:
    security:
      allowInsecureImages: true
  primary:
    persistence:
      enabled: false
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
