name: Day21 Backend CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 8 * * 1'

jobs:
  backend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Show GitHub Context
        run: echo "Triggered by ${{ github.event_name }} on branch ${{ github.ref_name }}"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Backend Tests
        run: npm test
